### ISSUE TITLE
afulnx fails to build on Ubuntu 18.04.5LTS 4.15.0-124-generic

### ISSUE THREAD

**Issue by torehl** [Zibri/afulnx#3]
Hi,
      fail to build on latest Ubuntu 18.04.5LTS. You fix?

root@lizhi:~/Downloads/Supermicro/X9DRG-HF/Bios/3.3/X9DRGH8.719/afulnx-release/afulnx64# uname -ar
Linux lizhi 4.15.0-124-generic #127-Ubuntu SMP Fri Nov 6 10:54:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@lizhi:~/Downloads/Supermicro/X9DRG-HF/Bios/3.3/X9DRGH8.719/afulnx-release/afulnx64# ./afulnx_64 /MAKEDRV KERNEL=/lib/modules/4.15.0-124-generic/build 
 - Program initializing .. 
 - Make AFULNX driver .... In file included from /root/Downloads/Supermicro/X9DRG-HF/Bios/3.3/X9DRGH8.719/afulnx-release/afulnx64/.temp/amiwrap.c:17:0:
./arch/x86/include/asm/uaccess.h: In function ‘set_fs’:
./arch/x86/include/asm/uaccess.h:32:9: error: dereferencing pointer to incomplete type ‘struct task_struct’
  current->thread.addr_limit = fs;
         ^~
make[2]: *** [/root/Downloads/Supermicro/X9DRG-HF/Bios/3.3/X9DRGH8.719/afulnx-release/afulnx64/.temp/amiwrap.o] Error 1
make[1]: *** [_module_/root/Downloads/Supermicro/X9DRG-HF/Bios/3.3/X9DRGH8.719/afulnx-release/afulnx64/.temp] Error 2
make: *** [default] Error 2
fail
10 - Error: Unable to load driver.
root@lizhi:~/Downloads/Supermicro/X9DRG-HF/Bios/3.3/X9DRGH8.719/afulnx-release/afulnx64# 

Brgds,
Tore
